services:
  css:
    user: 1000:1000
    image: ghcr.io/anon-123456789/css-docker:latest
    environment:
      - MAX_PLAYERS=6
      - MAP=cs_office
      - PASSWORD=replace_this
      - LOGIN_TOKEN=replace_this
      - ARGS=""
    ports:
      - 27015:27015
      - 27015:27015/udp
    volumes:
      - ./server:/server